# For now this is just a sketch, moved out of .github-workflows to avoid running
name: Deploy App to AWS ECS

on:
  push:
    branches: [ dev, main ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  ECR_REPO: unicus/ruter
  ECS_CLUSTER: ruter-chatbot
  SERVICE_DEV: chatbot-staging-service
  SERVICE_PROD: chatbot-staging-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650468121619:role/GitHubActionsDeployRole
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION  }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "TAG=prod-latest" >> $GITHUB_ENV
            echo "SERVICE=${{ env.SERVICE_PROD }}" >> $GITHUB_ENV
          else
            echo "TAG=dev-latest" >> $GITHUB_ENV
            echo "SERVICE=${{ env.SERVICE_DEV  }}" >> $GITHUB_ENV
          fi
      
      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile.prod \
            -t ${{ env.ECR_REPO }}:${TAG} \
            .
      
      - name: Push to ECR
        run: | 

          IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${TAG}"
          docker tag ${ECR_REPO}:${TAG} $IMAGE_URI
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
      
      - name: Deploy to ECS Service
        uses: aws-actions/amazon-ecs-deploy@v2
        with:
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE_URI }}
          wait-for-service-stability: true